export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const EMPTY_CART = "EMPTY_CART"
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";


// REQUEST FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_REQUEST = "BEGIN_PRODUCTS_REQUEST";
export const SUCCESS_PRODUCTS_REQUEST = "SUCCESS_PRODUCTS_REQUEST";
export const FAIL_PRODUCTS_REQUEST = "FAIL_PRODUCTS_REQUEST";

// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// CREATE ORDER
export const BEGIN_ORDER_CREATE = 'BEGIN_ORDER_CREATE';
export const SUCCESS_ORDER_CREATE = 'SUCCESS_ORDER_CREATE';
export const FAIL_ORDER_CREATE = 'FAIL_ORDER_CREATE';
export const RESET_ORDER = 'RESET_ORDER';

// PAY ORDER
export const BEGIN_ORDER_PAY = 'BEGIN_ORDER_PAY';
export const SUCCESS_ORDER_PAY = 'SUCCESS_ORDER_PAY';
export const FAIL_ORDER_PAY = 'FAIL_ORDER_PAY';
export const RESET_ORDER_PAY = 'RESET_ORDER_PAY';

// GET ORDER DETAIL
export const BEGIN_ORDER_DETAIL = 'BEGIN_ORDER_DETAIL';
export const SUCCESS_ORDER_DETAIL = 'SUCCESS_ORDER_DETAIL';
export const FAIL_ORDER_DETAIL = 'FAIL_ORDER_DETAIL';

//GET ARTIST MOMENT
export const BEGIN_MOMENT_REQUEST = 'BEGIN_MOMENT_REQUEST';
export const SUCCESS_MOMENT_REQUEST = 'SUCCESS_MOMENT_REQUEST';
export const FAIL_MOMENT_REQUEST = 'FAIL_MOMENT_REQUEST';

export const SET_MOMENT_CONTENT = 'SET_MOMENT_CONTENT';
export const SET_MOMENT_DETAIL = 'SET_MOMENT_DETAIL';


export const BEGIN_ARTISTPOST_REQUEST = 'BEGIN_ARTISTPOST_REQUEST';
export const SUCCESS_ARTISTPOST_REQUEST = 'SUCCESS_ARTISTPOST_REQUEST';
export const FAIL_ARTISTPOST_REQUEST = 'FAIL_ARTISTPOST_REQUEST';
export const SET_ARTISTPOST_CONTENT = 'SET_ARTISTPOST_CONTENT';
