export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

// REQUEST FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_REQUEST = "BEGIN_PRODUCTS_REQUEST";
export const SUCCESS_PRODUCTS_REQUEST = "SUCCESS_PRODUCTS_REQUEST";
export const FAIL_PRODUCTS_REQUEST = "FAIL_PRODUCTS_REQUEST";

// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";